name: Lint client application

on: [push]  

jobs:
  client-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node 13.12
      uses: actions/setup-node@v1
      with:
        node-version: '13.12'
    - name: Install dependency
      run: |
        cd client
        yarn install
    - name: Lint
      run: |
        cd client
        yarn lint