name: Lint server application

on: [push]  

jobs:
  server-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - run: |
        cd server
        pip install pylint
        pip install -r requirements.txt
        pylint **/*.py
