name: Lint scripts folder

on: [push]  

jobs:
  scripts-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Flake8 Scripts
      uses: TrueBrain/actions-flake8@master
      with:
        path: scripts
